### ISSUE TITLE
Missing MIME type causes exception to be thrown on some phones

### ISSUE THREAD

**Issue by branimirteodorovic** [madnik7/PortableStorage#1]
When trying to create write stream on Huawei phone, the app throws an exception with message "mimeType can't be null".
Is there a chance you can add optional MIME type parameter for CreateStream method?

**Comment by madnik7** [comment]
@branimirteodorovic As it is a portable storage, setting MIME explicitly makes no sense for other providers. 
I have set MIME to "application/octet-stream" in SAF android provider and published a new Nuget version 1.2.71. 
Let me know if it doesn't work for you.

**Comment by branimirteodorovic** [comment]
It works now. Thanks
